dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make all
  - cd test
  - ./JsonMaxTests
