dist: trusty
language: cpp
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-7
      - g++-7
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd test

#  Run tests
  - ./JsonMaxTests

#  Check if demos with single include JsonMax.h work
  - ./JsonMaxDemoSweets
  - ./JsonMaxDemoWeather
