sudo: false
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8


install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi

script:
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd test
  - ./JsonMaxTests
